### ISSUE TITLE
Feed contains posts from muted accounts

### ISSUE THREAD

**Issue by YtvwlD** [pkreissel/foryoufeed#2]
If I mute an account, I don't want to see its posts.

Otherwise, this is very nice, thank you. :)

**Comment by YtvwlD** [comment]
Hm, I've updated to 285e5e9f8ba8e5477358e1344c535ac85677014c and I still get posts from accounts I've muted. (It looks much nicer, though.)

**Comment by pkreissel** [comment]
Finally Fixed with [this](https://github.com/pkreissel/fedialgo/pull/3).

**Comment by YtvwlD** [comment]
I've updated to ffa5811d5a65d8e80c3ad031448f0b4e9d26757a and it still happens, I'm afraid.
